# Generated by Django 5.2.7 on 2025-11-01 18:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('beds', models.PositiveIntegerField(default=0)),
                ('bathrooms', models.PositiveIntegerField(default=0)),
                ('area', models.PositiveIntegerField(help_text='Area in square feet')),
                ('property_description', models.TextField(max_length=1000)),
                ('image', models.ImageField(blank=True, null=True, upload_to='property_images/')),
                ('electricity', models.BooleanField(default=False)),
                ('water', models.BooleanField(default=False)),
                ('internet', models.BooleanField(default=False)),
                ('airconditioning', models.BooleanField(default=False)),
                ('kitchen', models.BooleanField(default=False)),
                ('shared_kitchen', models.BooleanField(default=False)),
                ('private_bathroom', models.BooleanField(default=False)),
                ('shared_bathroom', models.BooleanField(default=False)),
                ('secure_locks', models.BooleanField(default=False)),
                ('cctv', models.BooleanField(default=False)),
                ('gated_compound', models.BooleanField(default=False)),
                ('security_guard', models.BooleanField(default=False)),
                ('parking', models.BooleanField(default=False)),
                ('furnished', models.BooleanField(default=False)),
                ('pet_friendly', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('landlord', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='properties', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
