# Generated by Django 5.2.7 on 2025-11-18 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landLordPage', '0003_alter_property_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='rejection_reason',
            field=models.TextField(blank=True, help_text='Reason for rejection if applicable', null=True),
        ),
    ]
