# Generated by Django 5.2.7 on 2025-12-08 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('renterPage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertycomment',
            name='rating',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
