# Generated by Django 5.2.7 on 2025-12-03 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_role',
            field=models.CharField(choices=[('renter', 'Renter'), ('landlord', 'Landlord'), ('coordinator', 'Coordinator')], default='renter', max_length=20),
        ),
    ]
